[project]
name = "pyshell"
version = "0.1.0"
description = "Execute shell scripts as Python functions with proper error handling"
authors = [
    {name = "Sisung Kim",email = "sisung.kim1@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
]
